version: "3.8"

services:
  vault:
    image: hashicorp/vault:1.15.0
    volumes:
      - ./config.hcl:/vault/config/config.hcl:ro
      - vault-file:/vault/file
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
    cap_add:
      - IPC_LOCK
    command: server -config=/vault/config/config.hcl
volumes:
  vault-file: 